### ISSUE TITLE
[minor] cleaner sampling

### ISSUE THREAD

**Issue by jonocarroll** [adam-gruer/bortles#1]
Love it!

FYI, you can sample a vector directly. Rather than this:

https://github.com/adam-gruer/bortles/blob/73cf2f7e10b483ab8c9a16c6c7b63c178abc3238/R/fork.R#L12

You can just `sample(x, 1)`...

``` r
files <- c("holy", "mother", "forking", "shirtballs")

set.seed(2)
files[sample(seq_along(files), 1)]
#> [1] "holy"
files[sample(seq_along(files), 1)]
#> [1] "forking"

set.seed(2)
sample(files, 1)
#> [1] "holy"
sample(files, 1)
#> [1] "forking"
```

Then again... 

![](https://media.giphy.com/media/etUt73tGMTPnuvUtPA/giphy.gif)

**Comment by adam-gruer** [comment]
thanks @jonocarroll 
![goodperson](https://media.giphy.com/media/l3mZjsC38twDeMLOE/giphy.gif)
